[[plugins]]
package = "@netlify/plugin-nextjs"

[[edge_functions]]
path = "/test"
function = "hello"


[[redirects]]
  from = "/images/"
  to = "/.netlify/builders/helloworld"
  status = 200
  force = true