import Head from "next/head";
// import Image from 'next/image'
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netlify Edge Function</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Next.js!</h1>

        <p className={styles.description}>
          <a
            className={styles.link}
            href="https://example-edge-function-next.netlify.app/test"
          >
            Click to test the Location Edge Functions
          </a>
        </p>
        <p className={styles.description}>
          <a
            className={styles.link}
            href="https://example-edge-function-next.netlify.app/location"
          >
            Click to test the location Edge Functions
          </a>
        </p>
        <p className={styles.description}>
          <a
            className={styles.link}
            href="https://example-edge-function-next.netlify.app/geolocation"
          >
            Click to test the location typescript Edge Functions
          </a>
        </p>
      </main>
    </div>
  );
}
