import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={content}>
            <h1>See Every Color!</h1>
            <p>
                Enter a color in the URL to see how that color renders in your browser.
            </p>
            <p>The following URL formats are supported:</p>
            <ul>
                <li>
                    Named colors<br /> Format: <code>/named/:colorName</code><br /> Example: <a href="/named/tomato">/named/tomato</a>
                </li>
                <li>
                    Hex colors<br /> Format: <code>/hex/:hexValue</code><br /> Example: <a href="/hex/bada55">/hex/bada55</a>
                </li>
                <li>
                    RGB colors<br /> Format: <code>/rgb/:red/:green/:blue</code><br /> Example: <a href="/rgb/80/90/100">/rgb/80/90/100</a>
                </li>
            </ul>
        </div>
      </main>

    </div>
  )
}
