import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Testing <a href="https://cosmic-duckanoo-0fe87b.netlify.app/test">Hello World Edge Functions</a>
        </p>

        <p className={styles.description}>
          Testing <a href="https://cosmic-duckanoo-0fe87b.netlify.app/odb">Hello World Edge Functions</a>
        </p>

      </main>

    </div>
  )
}
